package.json, src/system/grid.test.ts, src/system/grid.ts, src/system/keys.ts
=> Add grid utility support

packages/core/src/k.ts
Refactor htmlTags, and remove isHTMLElement method.
=> Refactor HTML Tags.

README.md, packages/next-plugin/README.md
The gitkeep file was still there, so I removed it while I was at it. 1341ae0
=> Fix incorrect setup example for Next.js

packages/system/src/position.ts
I  fixed css position values at the "bottom" and "inset". 
If you have some opinions please tell me.
Thank you for reviewing.
=> fix position 'bottom, inset' css prop values

configs/jest-preset/package.json, package.json, packages/babel-plugin/package.json, packages/core/package.json, packages/sheet/tsconfig.json, packages/system/tsconfig.json, packages/webpack-plugin/package.json, pnpm-lock.yaml
Removed unnecessary dependencies and relocated package specific dependencies from the root to the appropriate package.
=> Organize package dependencies

.gitignore, example/vite/src/App.tsx, packages/babel-plugin/CHANGELOG.md, packages/babel-plugin/package.json, packages/babel-plugin/src/processK.ts, packages/babel-plugin/src/processTaggedTemplateExpression.ts, packages/babel-plugin/src/visitor.ts, packages/core/CHANGELOG.md, packages/core/package.json, packages/next-plugin/CHANGELOG.md, packages/next-plugin/package.json, packages/sheet/CHANGELOG.md, packages/sheet/package.json, packages/system/CHANGELOG.md, packages/system/package.json, packages/vite/CHANGELOG.md, packages/vite/package.json, packages/webpack-plugin/CHANGELOG.md, packages/webpack-plugin/package.json
=> Overriding styles defined within tagged template literals using style props

.gitignore, example/vite/src/App.tsx, packages/babel-plugin/CHANGELOG.md, packages/babel-plugin/package.json, packages/next-plugin/CHANGELOG.md, packages/next-plugin/package.json, packages/sheet/CHANGELOG.md, packages/sheet/package.json, packages/sheet/src/cache.test.ts, packages/sheet/src/cache.ts, packages/sheet/src/index.ts, packages/sheet/src/sheet.test.ts, packages/sheet/src/sheet.ts, packages/sheet/src/styleMap.test.ts, packages/sheet/src/styleMap.ts, packages/system/CHANGELOG.md, packages/system/package.json, packages/system/src/compose.ts, packages/vite/CHANGELOG.md, packages/vite/package.json, packages/vite/src/index.ts, packages/webpack-plugin/CHANGELOG.md, packages/webpack-plugin/package.json, packages/webpack-plugin/src/loader.ts, packages/webpack-plugin/src/plugin.ts
#41
Plan: https://github.com/poteboy/kuma-ui/issues/41#issuecomment-1540349283
=> Unnecessary CSS accumulates with HMR 

example/next/package.json, packages/next-plugin/package.json, packages/next-plugin/src/index.ts, packages/webpack-plugin/package.json, packages/webpack-plugin/src/loader.ts, packages/webpack-plugin/src/virtualLoader.ts, pnpm-lock.yaml
This PR is a continuation of the work done in [#43](https://github.com/poteboy/kuma-ui/pull/43). Unfortunately, the original PR was mistakenly closed. I've reopened it here to incorporate the changes and continue the discussion.
=> Change css injection method from runtime inject to virtualLoader file. 

.github/workflows/main.yml, .github/workflows/release.yml, example/next/tsconfig.json
The CI process was failing as seen [here](https://github.com/poteboy/kuma-ui/actions/runs/4956052533/jobs/8866059975). To address this, I have changed the moduleResolution setting from node to bundler for the `example/webpack`. Additionally, I have upgraded the Node.js version used in the CI process from v14 to v16.
=> Addressing CI Failing Issue

packages/system/src/border.ts, packages/system/src/color.ts, packages/system/src/flex.ts, packages/system/src/grid.ts, packages/system/src/layout.ts, packages/system/src/position.ts, packages/system/src/shadow.ts, packages/system/src/space.ts, packages/system/src/types.ts, packages/system/src/typography.ts
Added js-doc to css props type.
#52
=> Added js-doc to css props type

README.md, example/vite/src/App.tsx, packages/babel-plugin/README.md, packages/babel-plugin/src/extractStyleProps/fromObject.ts, packages/babel-plugin/src/processCSS.ts, packages/babel-plugin/src/processHTMLTag.ts, packages/babel-plugin/src/replaceK.ts, packages/babel-plugin/src/visitor.ts, packages/core/README.md, packages/core/src/css.ts, packages/core/src/index.ts, packages/core/src/k.ts, packages/next-plugin/README.md, packages/sheet/README.md, packages/system/README.md, packages/vite/README.md, packages/webpack-plugin/README.md, pnpm-lock.yaml, pnpm-workspace.yaml
The css function allows users to define styles either as tagged template literals or as JavaScript objects, similar to libraries like Emotion.
```tsx
import { css } from '@kuma-ui/core';
const Component = () => (
<div className={css`font-size: 24px; color: red;`} />
);
// or
const Component = () => (
<div
className={css({
fontSize: '24px',
color: 'red',
})}
/>
);
```
=> Add `css` Function

packages/babel-plugin/CHANGELOG.md, packages/babel-plugin/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/next-plugin/CHANGELOG.md, packages/next-plugin/package.json, packages/sheet/CHANGELOG.md, packages/sheet/package.json, packages/system/CHANGELOG.md, packages/system/package.json, packages/vite/CHANGELOG.md, packages/vite/package.json, packages/webpack-plugin/CHANGELOG.md, packages/webpack-plugin/package.json, pnpm-lock.yaml
Changes include followings:
- [https://github.com/poteboy/kuma-ui/pull/55](https://github.com/poteboy/kuma-ui/pull/55)
- [https://github.com/poteboy/kuma-ui/pull/54](https://github.com/poteboy/kuma-ui/pull/54)
- [https://github.com/poteboy/kuma-ui/pull/51](https://github.com/poteboy/kuma-ui/pull/51)
=> Release 5/21/2023

.github/workflows/main.yml, .github/workflows/release.yml, package.json, pnpm-lock.yaml
Due to a pnpm version mismatch, it was broken, so we narrowed down the version to v8.
1. The specification of lock file is different between v8 and v7, so they are unified in v8.
2. Deleted lock file once and refreshed it.
I would like you to verify that it is not broken by local and Merge it.
=> Fixed pnpm lock changing every time.

packages/babel-plugin/package.json, packages/babel-plugin/src/__test__/__fixtures__/base/code.js, packages/babel-plugin/src/__test__/__fixtures__/base/output.js, packages/babel-plugin/src/__test__/__snapshots__/css.test.ts.snap, packages/babel-plugin/src/__test__/css.test.ts, pnpm-lock.yaml, tsup.config.ts
=> Add Tests for Kuma UI Babel Plugin 

packages/babel-plugin/package.json, packages/babel-plugin/src/__test__/__fixtures__/base/code.js, packages/babel-plugin/src/__test__/__fixtures__/base/output.js, packages/babel-plugin/src/__test__/__snapshots__/css.test.ts.snap, packages/babel-plugin/src/__test__/css.test.ts, pnpm-lock.yaml, tsup.config.ts
=>  Add Tests for Kuma UI Babel Plugin

packages/babel-plugin/CHANGELOG.md, packages/babel-plugin/package.json, packages/next-plugin/CHANGELOG.md, packages/next-plugin/package.json, packages/vite/CHANGELOG.md, packages/vite/package.json, packages/webpack-plugin/CHANGELOG.md, packages/webpack-plugin/package.json
- [https://github.com/poteboy/kuma-ui/pull/63](https://github.com/poteboy/kuma-ui/pull/63)
- [https://github.com/poteboy/kuma-ui/pull/62](https://github.com/poteboy/kuma-ui/pull/62)
=> Release 5/24/2023

packages/webpack-plugin/src/loader.ts
=> Fix CSS file path not resolving on Windows

package.json, packages/babel-plugin/CHANGELOG.md, packages/babel-plugin/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/next-plugin/CHANGELOG.md, packages/next-plugin/package.json, packages/sheet/CHANGELOG.md, packages/sheet/package.json, packages/system/CHANGELOG.md, packages/system/package.json, packages/vite/CHANGELOG.md, packages/vite/package.json, packages/webpack-plugin/CHANGELOG.md, packages/webpack-plugin/package.json, website/docs/styled-system.md, website/src/components/header.tsx, website/src/components/markdown.tsx
Instead of using `typeof document !== 'undefined'`, I've defined a `rendered` state with the `useReducer` hook that only changes to true once the component has mounted as suggested by the official doc: https://nextjs.org/docs/messages/react-hydration-error.
=> Fix React Hydration Error

.changeset/config.json, .github/workflows/main.yml, .github/workflows/release.yml, README.md, package.json, pnpm-lock.yaml
I tried to automate the changeset release process with CI.
In order to use the automation, you seem to need to install [this bot](https://github.com/apps/changeset-bot) to this repository. And it might be necessary to give the bot permissions to write and create PRs  in github settings.
And, I need your help because I have not been able to test with this repository and have been testing with my own repository, so please let me know if there are any problems. I hope we can solve them together.
=> Automate Changeset Release through CI

.changeset/add-sync-files.md, package.json, packages/babel-plugin/README.md, packages/core/README.md, packages/next-plugin/README.md, packages/sheet/README.md, packages/system/README.md, packages/vite/README.md, packages/webpack-plugin/README.md, scripts/sync-files.js
Added script to sync `./README.md` to each `packages/README.md` at pre-commit to resolve the following issue.
https://github.com/poteboy/kuma-ui/issues/96
- Copy the contents of `./README.md` to `packages/README.md`.
- If there are no diffs, it is not executed.
- Modified the `lint-staged` section of package.json to run at pre-commit time.
**(Please run `pnpm husky install` after the merge to update your githook)**
The problem is that `packages/README.md` and `./README.md` will be executed even when there is no diff.
However, since the timing of execution is at pre-commit and the differences remain on the stage after commit, no action was taken.
(We figured that if there were developers who only changed `package/README.md` they would notice at this time.)
Please let me know if there are …
=> chore: Automate Synchronization of README Files Across Packages

example/vite/src/App.tsx, packages/babel-plugin/src/__test__/__snapshots__/k.test.ts.snap, packages/babel-plugin/src/__test__/__snapshots__/styled.test.ts.snap, packages/babel-plugin/src/__test__/css.test.ts, packages/babel-plugin/src/__test__/k.test.ts, packages/babel-plugin/src/__test__/styled.test.ts, packages/babel-plugin/src/__test__/testUtils.ts, packages/babel-plugin/src/transform.ts, packages/compiler/src/collector/collect.ts, packages/compiler/src/collector/pseudo.ts, packages/compiler/src/components/Box.ts, packages/compiler/src/components/Button.ts, packages/compiler/src/components/Flex.ts, packages/compiler/src/components/Heading.ts, packages/compiler/src/components/Spacer.ts, packages/compiler/src/components/Text.ts, packages/sheet/src/sheet.test.ts, packages/vite/src/index.ts
It seems that the switch from Babel Plugin to TS morph in PR #131 has caused the pseudo props to break.
=> Breakage of Pseudo Props Following Migration from Babel Plugin to TS Morph

packages/system/src/column.test.ts, packages/system/src/column.ts, packages/system/src/compose.test.ts, packages/system/src/compose.ts, packages/system/src/index.ts, packages/system/src/keys.ts
=> add: column css

website/src/components/home/hero.tsx
=> Landing Page Design

packages/compiler/src/collector/collect.ts, packages/compiler/src/collector/expression.ts, website/src/components/example/Spacer.tsx, website/src/components/example/index.ts, website/src/pages/docs/Components/Box.mdx, website/src/pages/docs/Components/Spacer.mdx, website/src/pages/docs/Components/_meta.json
This PR addresses a bug in the Spacer handler that failed to recognize horizontal={true} prop. It also enriches the documentation for the Spacer component.
=> Fix Spacer Handler and Enhance Documentation

example/next-app-router/src/app/page.tsx, packages/babel-plugin/src/__test__/__snapshots__/styled.test.ts.snap, packages/sheet/src/sheet.ts, packages/system/src/generator.ts
=> fix: improve className prefix

packages/system/src/compose.test.ts, packages/system/src/compose.ts, packages/system/src/index.ts, packages/system/src/keys.ts, packages/system/src/mask.test.ts, packages/system/src/mask.ts
=> add: mask* CSS to system

packages/core/src/components/types.ts
=> fix(core): enhance type of component color-related props

website/src/pages/docs/install.mdx
=> docs(website): add ssr section

website/src/pages/docs/Components/UtilityProps.mdx
=> Fix typo in docs

website/src/components/home/hero.tsx
This PR addresses an issue raised in #220 and provides a follow-up to the PR that was reverted in #206.
=> Fix Color Scheme Listener for Compatibility with OS and Nextra

packages/babel-plugin/src/__test__/css.test.ts, packages/babel-plugin/src/__test__/k.test.ts, packages/babel-plugin/src/__test__/styled.test.ts, packages/babel-plugin/src/__test__/testUtils.ts, packages/babel-plugin/src/transform.ts, packages/vite/src/index.ts, packages/webpack-plugin/src/loader.ts
relate to https://github.com/poteboy/kuma-ui/pull/235.
=> refactor: remove unnecessary async

website/src/pages/docs/API/styled.mdx
Fixes a typo on the page for the `styled` api
=> Fix typo in Update styled.mdx

.github/FUNDING.yml
Add the following links to GitHub Sponsors 🐻‍❄️
- GitHub Users
- @poteboy 
- @taishinaritomi 
- @kotarella1110 
- open collective
- https://opencollective.com/kuma-ui
=> Add links to GitHub Sponsors 💚

.github/workflows/main.yml, package.json, packages/babel-plugin/src/ensureReactImport.ts, packages/core/src/components/Box/react/StaticBox.tsx, packages/core/src/components/Heading/react.tsx, packages/core/src/components/Spacer/handler.ts, packages/core/src/components/types.ts, packages/core/src/k.ts, packages/core/src/registry/StyleSheetRegistry.ts, packages/core/src/theme.ts, packages/next-plugin/src/index.ts, packages/system/src/compose.ts, packages/system/src/grid.test.ts, packages/system/src/space.ts
This PR introduces enforcement of code format on CI.
Currently some files are not formatted and it will causes unrelated changes in PRs.
=> Enforce prettier format on CI

.github/workflows/main.yml, packages/core/src/components/Box/index.ts
https://github.com/kuma-ui/kuma-ui/pull/265#issuecomment-1666664520
- `.github/workflows/main.yml` should only be run when `packages/**` changes
- Exclude the `experimental` branch as it is not used
=> Fix workflows

.changeset/green-buckets-approve.md, packages/system/src/background.ts, packages/system/src/color.ts, packages/system/src/types.ts
Followup of https://github.com/kuma-ui/kuma-ui/pull/259#discussion_r1284088813
=> Refactor types in system package

.changeset/few-mugs-approve.md, packages/core/src/theme.test.ts, packages/sheet/src/theme.ts, packages/system/src/layout.test.ts, packages/system/src/layout.ts, packages/system/src/valueConverters.test.ts, packages/system/src/valueConverters.ts, website/src/pages/docs/Theme/ThemeTokens.mdx
=> Add support for size token

.changeset/light-windows-do.md, packages/sheet/src/theme.ts, packages/system/src/border.test.ts, packages/system/src/border.ts, packages/system/src/valueConverters.test.ts, packages/system/src/valueConverters.ts, website/src/pages/docs/Theme/ThemeTokens.mdx
SSIA https://github.com/kuma-ui/kuma-ui/issues/257
=> Add support for radius token

.changeset/lucky-crabs-hug.md, packages/core/src/theme.test.ts, packages/sheet/src/theme.ts, packages/system/src/layout.test.ts, packages/system/src/layout.ts, packages/system/src/valueConverters.test.ts, packages/system/src/valueConverters.ts, website/src/pages/docs/Theme/ThemeTokens.mdx
=> Add support for z-index token

website/src/pages/docs/Theme/CustomizingTheme.mdx, website/src/pages/docs/Theme/ThemeTokens.mdx
This PR updates the list of available theme tokens in our documentation to reflect the recently added tokens. Thanks to the efforts of @yukukotani  and @taishinaritomi , all planned theme tokens for Kuma UI have now been incorporated.
=> Update Documentation for Completed Theme Tokens

.gitignore, example/vite/package.json, example/vite/vite.config.ts, pnpm-lock.yaml
=> feat: add vite-plugin-inspect

website/src/pages/docs/Recepies/Optimization.mdx, website/src/pages/docs/Recepies/_meta.json
=> Adding an Optimization Guide to the Documentation

.changeset/weak-jokes-smash.md, packages/next-plugin/src/index.ts, packages/webpack-plugin/src/cssLoader.ts, packages/webpack-plugin/src/loader.ts, packages/webpack-plugin/src/plugin.ts
=> refactor(next): Liberation from the curse of '.next/cache/kuma/*.css'

.changeset/wet-rabbits-kick.md, packages/compiler/src/__test__/__snapshots__/styled.test.ts.snap, packages/compiler/src/__test__/styled.test.ts, packages/compiler/src/processTaggedTemplateExpression.ts
=> check 'styled' import binding before transforming

.changeset/tasty-birds-sip.md, packages/system/src/background.test.ts, packages/system/src/background.ts, packages/system/src/color.test.ts, packages/system/src/color.ts, packages/system/src/compose.test.ts, packages/system/src/compose.ts, packages/system/src/effect.test.ts, packages/system/src/effect.ts, packages/system/src/filter.test.ts, packages/system/src/filter.ts, packages/system/src/flex.test.ts, packages/system/src/flex.ts, packages/system/src/index.ts, packages/system/src/keys.ts, packages/system/src/layout.test.ts, packages/system/src/layout.ts
This PR adds the following css properties:
* overflowX
* overflowY
* aspectRatio
* filter
* backdropFilter
* backgroundBlendMode / bgBlendMode
* boxSizing
* float
* clear
* objectFit
* objectPosition
* placeItems
* placeContent
* resize
* verticalAlign
* userSelect
* visibility
* clipPath
If there is something to be changed, I'll be glad to make any changes :)
( related to #150 )
=> add: lots of css properties

website/src/pages/docs/Theme/CustomizingTheme.mdx, website/src/pages/docs/Theme/ThemeTokens.mdx, website/src/pages/docs/install.mdx
- Correcting some capitalization.
- Add guide to setup in webpack.
=> docs: add guide to setup in webpack

.changeset/two-geckos-check.md, packages/babel-plugin/package.json, packages/babel-plugin/src/components/processComponents.ts, packages/compiler/package.json, packages/compiler/src/collector/collect.ts, packages/compiler/src/collector/expression.ts, packages/compiler/src/collector/pseudo.ts, packages/core/package.json, packages/core/src/components/componentList.ts, pnpm-lock.yaml
Fixes https://github.com/kuma-ui/kuma-ui/issues/288
=> chore: refactor ts-pattern to use switch/if-else

website/src/pages/docs/Components/Button.mdx
Fix minor lettercase inconsistencies
=> fix(docs): fix letter case

.changeset/smooth-otters-float.md, example/next-app-router/next.config.js, example/next-app-router/next.config.mjs, packages/next-plugin/src/index.ts, packages/webpack-plugin/package.json, packages/webpack-plugin/src/getUserTheme.ts, packages/webpack-plugin/src/loader.ts, packages/webpack-plugin/src/plugin.ts, packages/webpack-plugin/src/virtualLoader.ts, tsup.config.ts
=> fix: support next.config.mjs

.changeset/chatty-waves-shake.md, packages/system/src/__snapshots__/consumeStyleProps.test.ts.snap, packages/system/src/consumeStyleProps.test.ts, packages/system/src/consumeStyleProps.ts, packages/system/src/keys.ts, packages/system/src/props/layout.ts
I personally implemented this because it was inconvenient for me to do without it.
If you feel strongly that implementing this is a bad idea, feel free to ignore this PR.
But since there is a short hand on the margin, this may just be a forgotten implementation.
=> Add "w" shorthand for width property

.changeset/green-gifts-deliver.md, packages/core/src/utils/object.ts
Sorry it's a really small correction, but I made the correction.
=> Object type determination with strict equivalence operator

.changeset/hip-stingrays-fly.md, example/vite/src/App.tsx, packages/system/src/__snapshots__/consumeStyleProps.test.ts.snap, packages/system/src/consumeStyleProps.test.ts, packages/system/src/keys.ts, packages/system/src/props/effect.ts
close #414 ( part of #150 )
SSIA
=> Add Content & ContentVisibility Props To System
