src/babel-plugin/index.ts
src/babel-plugin/transform.ts
src/vite/index.ts

**Changes:**
1. In development mode, inject styles directly into the head tag instead of importing external CSS files. This speeds up hot-reloading and reduces unnecessary network requests.
2. In production mode, include the generated CSS file in the output bundle, based on the styles extracted from the AST. This ensures that the final build includes all necessary CSS, correctly linked to the HTML file.

Improved CSS handling in Vite plugin

---

README.md
package.json
playground/react-vite/package-lock.json
playground/react-vite/package.json
playground/react-vite/src/App.tsx
playground/react-vite/src/Box.tsx
playground/react-vite/vite.config.cjs
playground/react-vite/yarn.lock
src/babel-plugin/combineClassNames.ts
src/babel-plugin/extractStyleFromAST.ts
src/babel-plugin/processHTMLTag.ts
src/babel-plugin/visitor.ts
src/styled/index.ts

This pull request adds support for the following two features in styled components:
1. ~~Applying styles from a function in a TaggedTemplateExpression.~~
2. Combining both string CSS and function-based styles in a styled component.
~~These changes allow users to pass style functions in a TaggedTemplateExpression and mix them with string CSS~~. This makes it more flexible for users to define styles in their styled components.
Here's an example of how the new features work:
```js
const VStack = styled("div")`
display: flex;
`;
```
In this example, the display: flex; style is added directly as a string. The new implementation supports both styles in the styled function and combines them properly.

Add support for string CSS in styled components

---

README.md
package.json
playground/react-vite/src/App.tsx
playground/react-vite/src/Box.ts
src/babel-plugin/collectImportedStyled.ts
src/babel-plugin/processZ.ts
src/babel-plugin/visitor.ts
src/core/index.ts
src/core/styled.ts
src/core/z.ts

This PR implements the new 'z' API for creating zero-runtime styled components with utility props, as discussed in issue #14. This makes it easier and less verbose to create components with utility props without needing to create a separate styled component using the styled function.

Implement 'z' API for zero-runtime styled components with utility props

---

.github/workflows/main.yml
packages/babel-plugin/CHANGELOG.md
packages/babel-plugin/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/next-plugin/CHANGELOG.md
packages/next-plugin/package.json
packages/sheet/CHANGELOG.md
packages/sheet/package.json
packages/sheet/src/index.ts
packages/sheet/src/regex.test.ts
packages/sheet/src/regex.ts
packages/sheet/src/sheet.test.ts
packages/sheet/src/sheet.ts
packages/system/CHANGELOG.md
packages/system/package.json
packages/vite/CHANGELOG.md
packages/vite/package.json
packages/webpack-plugin/CHANGELOG.md
packages/webpack-plugin/package.json
pnpm-lock.yaml

Currently, the implementation uses a regex /\s/g to remove all whitespace characters in the CSS. This causes issues with some CSS properties that require whitespace to separate values, such as `padding: 10px 10px`.
To fix this, we should replace the global whitespace removal regex with a more specific regex that only removes whitespace around CSS property values. The new regex, `/((?<=:)\s+)|(\s+(?=;))/g`, should be used in place of the existing one.
This change will ensure that necessary whitespace is preserved within property values while still minimizing the CSS output.
Tasks:
1. Identify all instances where the /\s/g regex is used for CSS processing.
2. Replace the global whitespace removal regex with the new, more specific regex: `/((?<=:)\s+)|(\s+(?=;))/g`.
3. Implement the …

Replace global whitespace removal regex with more specific regex for CSS properties

---

.github/workflows/main.yml
.vscode/settings.json
package.json
packages/babel-plugin/package.json
packages/core/package.json
packages/next-plugin/package.json
packages/sheet/package.json
packages/system/package.json
packages/vite/package.json
packages/webpack-plugin/package.json
pnpm-lock.yaml
rollup.config.js
tsup.config.ts
turbo.json

This reverts commit 464bedb560f1371661f364b343dc372d1af7b51f.
Unfortunately, we encountered a new issue after applying the changes: `Cannot find module '@kuma-ui/core' or its corresponding type declarations.`It seems that we need to further investigate and address this problem.

Revert "Fix incorrect tsup config (#29)"

---

.vscode/settings.json

The reason for this change is that the TypeScript version used by VS Code should be left to each developer's individual environment.

Remove TypeScript version setting from workspace settings

---

example/next/package.json
example/vite/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

This PR aims to include the example directory in the workspace managed by pnpm. Previously, projects under the example directory were unable to reference other packages in the workspace due to not being included in the pnpm-workspace.yaml file.
Interestingly, in the past, even though the example directory was not included in pnpm-workspace.yaml, dependencies were still being properly resolved when running `pnpm i` from the root directory. This allowed projects under the example directory to function correctly. However, after re-cloning the repository, this no longer seems to be the case. The reason for this change in behavior is currently unknown.
By adding the example directory into pnpm-workspace.yaml, we aim to ensure these projects can directly reference and use other packages within …

Add example directory to the workspace

---

packages/babel-plugin/CHANGELOG.md
packages/babel-plugin/package.json
packages/next-plugin/CHANGELOG.md
packages/next-plugin/package.json
packages/system/CHANGELOG.md
packages/system/package.json
packages/system/src/keys.ts
packages/system/src/typography.ts
packages/vite/CHANGELOG.md
packages/vite/package.json
packages/webpack-plugin/CHANGELOG.md
packages/webpack-plugin/package.json

This PR includes two major changes:
1. It fixes an issue where `fontWeight` property was outputting as `font-weight: 600px;` instead of `font-weight: 600;` when the type of given prop is `number`. Now, both numbers and strings can be used with the fontWeight property.
2. It adds the CSS property `text-decoration` to the list of Style Props.

Fix fontWeight property and add textDecoration

---

example/next-app-router/src/app/layout.tsx
packages/next-plugin/src/index.ts

I have removed the dependency on `@babel-preset/env` from the Kuma UI Next.js plugin. This resolves an issue where `const` variables were being unnecessarily transpiled to `var`.
The problem becomes evident when using Next.js's font loader, which expects the loaded font to be assigned to a `const`. When our plugin transpiled `const` to `var`, it resulted in an error: 
```sh
next-app-router:build:   x Font loader calls must be assigned to a const
next-app-router:build:    ,-[/Users/keitafuruse/development/kuma-ui/example/next-app-router/src/app/layout.tsx:1:1]
next-app-router:build:  1 |     import React from "react";
next-app-router:build:  2 |     import { Inter } from "next/font/google";
next-app-router:build:  3 | ,-> var inter = Inter({
next-app-router:build:  4 | |     subsets: …
```

Remove dependency on @babel-preset/env from Next.js plugin

---

example/next-app-router/src/app/layout.tsx
packages/babel-plugin/src/extractStyleProps/fromJSX.ts
packages/babel-plugin/src/extractStyleProps/fromObject.ts
packages/babel-plugin/src/processHTMLTag.ts

#59 another plan
before
```ts
<k.div bg={'red'} className={inter.className}>
```
After
```ts
<k.div className={['kuma-*',  inter.className].join(" ")}>
```

Fix Overwriting of Existing ClassNames in Kuma UI

---

packages/system/src/color.ts
packages/system/src/compose.test.ts
packages/system/src/keys.ts

Previously, the `bg` prop was converted to `background-color`. We have now introduced a new `bgColor` prop for setting the background color specifically, and have repurposed the `bg` prop to correspond to the `background'`CSS property.

Refactor Background Property

---

packages/babel-plugin/src/processHTMLTag.ts
packages/system/src/effect.test.ts
packages/system/src/effect.ts
packages/system/src/keys.ts

This PR extends prop system to support `transform` and `transition` CSS properties.

Add 'effect' props for transform and transition styles

---

example/vite/src/App.tsx
packages/babel-plugin/CHANGELOG.md
packages/babel-plugin/package.json
packages/babel-plugin/src/processTaggedTemplateExpression.ts
packages/core/CHANGELOG.md
packages/core/package.json
packages/next-plugin/CHANGELOG.md
packages/next-plugin/package.json
packages/sheet/CHANGELOG.md
packages/sheet/package.json
packages/sheet/src/sheet.test.ts
packages/sheet/src/sheet.ts
packages/system/CHANGELOG.md
packages/system/package.json
packages/vite/CHANGELOG.md
packages/vite/package.json
packages/webpack-plugin/CHANGELOG.md
packages/webpack-plugin/package.json
pnpm-lock.yaml
website/docs/api.md
website/docs/responsive-styles.md
website/package.json
website/src/app/layout.tsx

Our current implementation of the `styled` function doesn't properly handle @media queries or pseudo-elements and pseudo-classes. The goal of this PR is to enhance our styled function to handle these additional CSS constructs.
Example:
```tsx
styled('div')`
display: flex;
flex-direction: row;
@media (max-width: 768px) {
flex-direction: column;
}
&:after {
content: " 🦄";
}
`
```

Enable parsing of @media and pseudo elements/classes in `styled` function

---

packages/core/package.json
packages/core/src/css.test.ts
packages/core/src/k.test.ts
packages/core/src/k.ts
packages/core/src/styled.test.ts
packages/core/vitest.config.ts
pnpm-lock.yaml

fixes the issue where an error was not being thrown when accessing properties of the `k`.
As is:
To be:

throw an error when accessing any property of 'k' at runtime

---

.changeset/stale-pigs-call.md
packages/babel-plugin/src/__test__/__snapshots__/css.test.ts.snap
packages/babel-plugin/src/__test__/__snapshots__/k.test.ts.snap
packages/babel-plugin/src/__test__/css.test.ts
packages/babel-plugin/src/__test__/k.test.ts
packages/babel-plugin/src/__test__/testUtils.ts

I have made improvements to include styles containing class names generated by the Babel plugin in the snapshots.
This ensures the quality of the style generation logic.
The changes I made are as follows:
- Modified to return the result of `transformSync` directly in `babelTransform`.
- Created a `getExpectSnapshot` function to generate the expected snapshot value containing the generated css from the return value of `transformSync`.
Since I checked out from the branch of https://github.com/poteboy/kuma-ui/pull/102, I would like you to merge this PR after merging that PR :pray:

test(babel-plugin): add generated css to snapshots

---

example/vite/src/App.tsx
packages/babel-plugin/src/__test__/__fixtures__/base/output.js
packages/babel-plugin/src/__test__/__snapshots__/css.test.ts.snap
packages/babel-plugin/src/__test__/__snapshots__/styled.test.ts.snap
packages/babel-plugin/src/__test__/styled.test.ts
packages/babel-plugin/src/importBox.ts
packages/babel-plugin/src/processTaggedTemplateExpression.ts
packages/babel-plugin/src/replaceKwithBox.ts
packages/babel-plugin/src/visitor.ts
packages/core/src/styled.ts

Refactor to improve JSX transformation functions

---

packages/system/src/keys.ts

Previously, we used a lookup operation with O(N) complexity to identify styled props using the `isStyledProp` function. This PR improves this by introducing memoization to cache results of previous prop lookups, thus reducing the time complexity to O(1) for repeated lookups. This optimization increases the efficiency of styled prop detection without altering functionality.

Optimize styled prop detection using memoization

---

packages/babel-plugin/src/hasCoreImportDeclaration.ts
packages/babel-plugin/src/visitor.ts

I have imported the latest experimental branch on my working branch and now I get the following error This is because the Babel plugin adds "@kuma-ui/core" imports to files that do not need them.
This PR adds a feature to check for the import of "@kuma-ui/core". The `hasCoreImportDeclaration` function is introduced to verify the presence of a core import declaration within the AST program. If the import is not found, the process is halted.

fix(babel-plugin): add import check for '@kuma-ui/core'

---

example/next-app-router/package.json
example/next-app-router/src/app/dynamic2.tsx
example/next-app-router/src/app/page.tsx
example/next-app-router/src/app/registry.tsx
packages/core/package.json
packages/next-plugin/package.json
pnpm-lock.yaml

If you're using a version of Next.js lower than v13.4.5 in the Next App Router environment and using Dynamic Props, a fouc (flash of unstyled content) may occur under certain conditions.
To address this issue, we will update the peer dependencies to encourage users to use Next.js v13.4.5 or higher.
https://github.com/poteboy/kuma-ui/assets/12913947/e081b65f-0a32-45cc-9d84-f8bb7fa2a47a
It seems that fouc occurs when importing @kuma-ui/core from a Server Component, but no fouc occurs when importing it from a Client Component.
For example, if you check out the branch in this pull request and modify dynamic2.tsx in example/next-app-router as follows, the fouc issue will be resolved:
```diff
+ "use client";
import { Box } from "@kuma-ui/core";
export function Dynamic2() {
return <Box bg={(() …
```

feat: update next peer dependencies to resolve fouc issue

---

example/next-app-router/src/app/dynamic.tsx
packages/core/package.json
packages/core/src/registry/StyleSheetRegistry.ts
pnpm-lock.yaml

In order to improve the runtime performance in the production environment, speedy mode is enabled. When speedy mode is enabled, styles are updated using the CSSStyleSheet's insertRule API. However, we discovered an issue where the insertRule API throws an error when passed dynamic props like media queries to Kuma UI component.
https://github.com/poteboy/kuma-ui/assets/12913947/5f30a8e5-678e-4b8a-9932-1888c1f49168
This problem occurs because the insertRule API only accepts one rule at a time, as stated in the following documentation:　https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule
> Thrown if more than one rule is given in the rule parameter.
In practice, if multiple rules are passed, an error occurs, as shown in the example below:
``` …
```

fix(core): fix speedy mode issue

---

example/next-app-router/src/app/page.tsx
packages/core/src/components/Box/react/types.ts
packages/core/src/components/Box/react/utils.ts
packages/core/src/components/Button/react.tsx
packages/core/src/components/Flex/react.tsx
packages/core/src/components/Heading/react.tsx
packages/core/src/components/Spacer/react.tsx
packages/core/src/components/Text/react.tsx
packages/core/src/components/types.ts
packages/core/src/theme.ts
packages/core/src/utils/types.ts

Here's an example of code completion when setting variants for `Box` and `Flex` in a theme:

feat(core): enhance variant type

---

packages/core/src/components/Box/react/utils.ts

I have identified a bug where the prefix of dynamic style class names was set to 🐻 instead of 🦄. Regrettably, I introduced this bug during the timing of https://github.com/poteboy/kuma-ui/pull/181 .
As is:
To be:

fix(core): fix className prefix issue at runtime

---

website/src/components/home/hero.tsx

On discord ([context](https://discord.com/channels/1119672933477011598/1128165291210326067/1128353327051194409))
- Adding `mix-blend-mode: plus-lighter` to the description in the hero component when viewed in dark mode
|Before|After|
|:--|:--|
| <img width="1493" alt="image" src="https://github.com/poteboy/kuma-ui/assets/8467289/11cbbf9c-df25-4df5-a00a-063ac2ce5cb9">  | <img width="1495" alt="image" src="https://github.com/poteboy/kuma-ui/assets/8467289/520b4294-76d2-445b-8571-8d4b0af13edb">  |

fix(website): Fix hero description visibility by adding `mix-blend-mode: plus-lighter` when using dark mode

---

website/src/components/home/hero.tsx

Revert "fix(website): Fix hero description visibility by adding `mix-blend-mode: plus-lighter` when using dark mode"

---

.changeset/afraid-apes-fold.md
example/next/tsconfig.json
example/vite/kuma.config.ts
example/vite/src/App.tsx
packages/sheet/src/theme.ts

this fixes #215.
Users have been experiencing a 'Cannot convert undefined or null to object' error when defining `kuma.config.ts` without setting breakpoints and then using responsive styles in Style Props (e.g., `flexDir={['column', 'row']}`).
This problem arises when there is a user-defined theme. The module bundler would override the theme as follows:
```ts
setUserTheme(userTheme: UserTheme) {
this._userTheme = userTheme;
}
```
In cases where breakpoints are not defined (i.e., are empty), this overrides the pre-existing defaultBreakpoints.
The oversight occurred because the bundler's plugin was type-asserting and embedding the theme in the following way, which will also need fixing eventually:
```ts
const config = eval(result.outputFiles[0].text, configPath) as {
default: unknown;
}; …
```

Preventing 'Cannot convert undefined or null to object' error when using responsive styles without defined breakpoints

---

packages/compiler/src/compile.ts

Deleted processing considered unnecessary in compiler/src/compile.ts.
I think the deleted processing is already compensated for by the processing in the find method.
Sorry for the trivial fix, but please check it out!

refactor: remove unnecessary processes

---

CONTRIBUTING.md
website/src/components/example/Heading.tsx
website/src/components/example/Text.tsx

Hi everyone!
This PR fixes the issues in the docs where the examples of the `Text` and `Heading` components are not visible in dark mode. To achieve this, I used the built-in `useTheme()` function that `nextra` provides.
I also added a bit to the `Contributing.md` file regarding the necessity to run `pnpm build`.
Closes #221

fix/docs: Fix `Text` and `Heading` style in docs/darkmode

---

.github/workflows/release.yml

The changesets action pushes the Git tag with the following line:
https://github.com/changesets/action/blob/2bb9bcbd6bf4996a55ce459a630a0aa699457f59/src/run.ts#L133
As you can see in the following log, the Git tag is not being created, so it won't be pushed:
https://github.com/poteboy/kuma-ui/actions/runs/5566908304/jobs/10168383439
Due to this issue, it is likely that the release notes are also not being generated.
To address this, we will add a command to generate the Git tag before publishing.
ref:
- https://github.com/pnpm/pnpm/issues/3586
- https://github.com/changesets/changesets/issues/612

ci(release): fix issue with git tags not being pushed

---

.github/workflows/release.yml

I received a report from @taishinaritomi that commands using && are not working correctly. It seems that they need to be converted to npm scripts or shell scripts.
After doing some research, I found that projects using pnpm are executing `changeset publish`:
- https://github.com/callstack/linaria
- https://github.com/vanilla-extract-css/vanilla-extract
As mentioned below, `changeset publish` includes Git tags:
https://github.com/changesets/changesets/blob/main/docs/command-line-options.md#tag
> The tag command creates git tags for the current version of all packages. The tags created are equivalent to those created by [changeset publish](https://github.com/changesets/changesets/blob/main/docs/command-line-options.md#publish), but the tag command does not publish anything to npm. …

ci(release): fix publish command

---

.changeset/rude-baboons-perform.md
packages/babel-plugin/src/transform.ts

There is a race condition in `transform()` in `@kuma-ui/babel-plugin` and in some cases, **styles will not be generated to CSS files**.
The probably of having accidentally missing CSS from prod build seems to be relatively high for reasonably big project.
(credit: this was reported in Discord, thanks the reporter (not sure about GitHub username)! I enjoyed debugging this)
1. `@kuma-ui/webpack-plugin` calls `transform()` from `@kuma-ui/babel-plugin` ([code](https://github.com/poteboy/kuma-ui/blob/76188d48ec19e96de6760dbb8d25c0b939d9ff6a/packages/webpack-plugin/src/loader.ts#L35-L35))
2. `transform()` in `@kuma-ui/babel-plugin` calls actual babel plugin via transformSync [here](https://github.com/poteboy/kuma-ui/blob/76188d48ec19e96de6760dbb8d25c0b939d9ff6a/packages/babel-plugin/src/transfor …

fix(babel-plugin): Race condition bug which can cause missing styles

---

packages/vite/src/index.ts

I want to release the implementation of using [virtual modules](https://vitejs.dev/guide/api-plugin.html#virtual-modules-convention) from https://github.com/poteboy/kuma-ui/pull/211 to import CSS.
dev server:
production build:

feat(vite): use virtual modules

---

packages/compiler/src/collector/collect.ts
packages/system/src/animation.test.ts
packages/system/src/animation.ts
packages/system/src/border.test.ts
packages/system/src/border.ts
packages/system/src/color.test.ts
packages/system/src/color.ts
packages/system/src/column.test.ts
packages/system/src/column.ts
packages/system/src/effect.ts
packages/system/src/flex.test.ts
packages/system/src/flex.ts
packages/system/src/font.test.ts
packages/system/src/font.ts
packages/system/src/grid.test.ts
packages/system/src/grid.ts
packages/system/src/layout.ts
packages/system/src/list.ts
packages/system/src/mask.test.ts
packages/system/src/mask.ts
packages/system/src/outline.test.ts
packages/system/src/outline.ts
packages/system/src/position.ts
packages/system/src/shadow.ts
packages/system/src/space.test.ts
packages/system/src/space.ts
packages/system/src/text.test.ts
packages/system/src/text.ts
packages/system/src/typography.test.ts
packages/system/src/typography.ts

(This original post has been edited to reflect correctly the current content of PR.)
kuma-ui has some utility props but if the value of the properties are zero, the properties will be removed in spite of it is necessary.
Currently this behavior can be dismissed by the workaround of using a string `"0"` instead of numerical `0`.
This PR makes the compiler recognize falsy values except `null` and `undefined`, as valid value and fixes the behavior.
<details>
<summary>Original Post</summary>
kuma-ui has some utility props that can change components' spaces, such as m and p but if the value of the properties are zero, the properties will be removed in spite of it is necessary.
Currently this behavior can be dismissed by the workaround of using a string "0" instead of numerical 0.
This PR makes …

fix: correctly compile falsy property values

---

.changeset/six-dancers-allow.md
packages/babel-plugin/src/__test__/__snapshots__/css.test.ts.snap
packages/babel-plugin/src/__test__/__snapshots__/styled.test.ts.snap
packages/babel-plugin/src/processTaggedTemplateExpression.ts
packages/babel-plugin/src/visitor.ts
packages/compiler/src/compile.ts
packages/compiler/src/processTaggedTemplateExpression.ts

We have decided to migrate the static extraction logic of TaggedTemplateExpression from babel-plugin to the compiler.
This means that the elements like styled and css API, which were previously statically extracted using babel, will now be extracted using ts-morph. As a result, we will be able to perform static extraction using ts-evaluate in the future, enabling smarter code processing.
This PR can be seen as a preparation to support interpolations and keyframes.

refactor: move tagged template expression from babel-plugin to compiler

---

README.md
package.json
packages/babel-plugin/README.md
packages/babel-plugin/package.json
packages/compiler/README.md
packages/compiler/package.json
packages/core/README.md
packages/core/package.json
packages/vite/README.md
packages/vite/package.json
packages/webpack-plugin/README.md
packages/webpack-plugin/package.json
website/src/components/example/Image.tsx
website/src/pages/docs/Components/Image.mdx
website/theme.config.jsx

After the repo's organization transition the other day, I noticed there were some additional places where the old owner's name still appears.
Although URLs still work correctly for now by redirecting, it should be fixed, as soon as possible.
This PR fix them.

(chore) Update repository references after the organization transition

---

example/vite/kuma.config.ts
example/vite/src/App.tsx
packages/compiler/src/extractor/extract.ts

This PR resolves an issue where variant styles were not overriding base styles as expected. 
For instance, consider the following theme configuration:
```ts:kuma.config.ts
const theme = createTheme({
components: {
Text: {
baseStyle: {
color: "red",
},
variants: {
primary: {
color: "green",
},
},
},
},
});
```
In this scenario, we'd expect `<Text variant={"primary"}>hello</Text>` to render green text, as the primary variant should override the baseStyle. However, the actual behavior was that the text color remained red.
Changes in this PR correct this issue, ensuring that variant styles properly override base styles.

Resolve base style override issue

---

website/src/components/example/Heading.tsx
website/src/components/example/Text.tsx

Hello maintainers! This is my first Pull Request, so I would appreciate help if there are any mistakes 😃 
Fixed an issue where the colors of the Text and Heading component of the website did not change correctly when the theme is set to System.
When I was reading the documentation to try out the Kuma UI, I noticed that the Text component assimilates the background color. Here is a screenshot:
ref: https://www.kuma-ui.com/docs/Components/Text
This does not happen if the theme is `dark`, but only if the theme is `system` .
To get the current theme including system in useTheme, it seems to be better to use `resolvedTheme` .
https://github.com/pacocoursey/next-themes#usetheme-1
In addition, the Heading component, which was searched in the project by useTheme and existed as another use point, …

fix(website): fix text color of example components from system theme

---

website/theme.config.jsx

In Kuma's documentation, the title logo becomes slightly transparent when in Dark Theme. To address this, I've set the mask-type of the logo SVG to "alpha".
**Before**:
**After**:

Fix Logo Transparency Issue in Dark Theme

---

.github/workflows/main.yml
.github/workflows/release.yml

Now, installing dependencies spent 10-15sec, becoming one-third!
Not cached: https://github.com/kuma-ui/kuma-ui/actions/runs/5774108606/job/15650715632?pr=269
Cached: https://github.com/kuma-ui/kuma-ui/actions/runs/5774120528/job/15650743609
The doc about pnpm cache on GitHub Actions here: https://pnpm.io/continuous-integration#github-actions

Enable pnpm cache on CI

---

.github/actions/setup-pnpm/action.yml
.github/workflows/main.yml
.github/workflows/release.yml

The current configuration of github actions is running pnpm install on each job.
This can be made common by using composite.
https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

 pnpm install in workflows uses composite action

---

.changeset/poor-rocks-worry.md
packages/vite/src/index.ts

resolve https://github.com/kuma-ui/kuma-ui/issues/273
I have successfully resolved the Hot Module Replacement (HMR) issue that was occurring in Vite versions v1.0.5 and later when using Kuma UI. The issue was related to CSS styles not being applied correctly during HMR.
Changes Made:
- Updated the Vite plugin to ensure proper CSS application during HMR.
- Added a hash to the imported CSS file.
This PR addresses the problem reported in issue https://github.com/kuma-ui/kuma-ui/issues/273, which was caused by changes introduced in PR https://github.com/kuma-ui/kuma-ui/pull/231. The issue was traced back to the way CSS was being handled during HMR.

fix(vite): fix hmr issue in vite v1.0.5 and later

---

.changeset/kind-mice-shake.md
packages/compiler/src/extractor/extract.ts
packages/compiler/src/utils/stableStringify.ts
packages/core/src/components/Box/react/utils.ts
packages/core/src/utils/stableStringify.test.ts
packages/core/src/utils/stableStringify.ts

Closes #246 
In short, Kuma UI's pseudo props support is basically broken.
Before this PR,  `generateKey` was generating something like `_hover:[object Object]|p:2`. After this PR, it uses `fast-json-stable-stringify` and it generates `{"_hover":{"color":"red"},"p":2}`, which includes nested values.
This is critical when using pseudo props. Because of this, when using pseudo props, most of the time styling was broken since actual values of pseudo stlying is not taken into account when taking a hash for style caching.
I used the following example to confirm the bug:
```tsx
import { Input } from "@kuma-ui/core";
function Demo() {
return (
<>
<Input m={2} _valid={{ bgColor: 'red' }} />
<Input m={2} _valid={{ bgColor: 'blue' }} />
</>
);
}
```
Both input elements are red and "bgColor: blue" …

fix: Replace broken generateKey with fast-json-stable-stringify for pseudo props

---

turbo.json

This PR fixes turborepo's filesystem cache to repair a stale website deployment to Vercel.
I didn't have Vercel permissions for this website, so I tried it at hand with the same environment settings I got from @poteboy .

build(website): fix cacheable filesystem outputs

---

.changeset/kind-socks-boil.md
packages/core/package.json
packages/core/src/components/Box/react/box.test.tsx
packages/core/src/tests/vitest.setup.ts
packages/core/tsconfig.json
packages/core/vitest.config.ts
pnpm-lock.yaml

This PR will set up @testing-library/jest-dom to be able to use toBeInTheDocument(), etc. in component testing.
I was going to try this issue https://github.com/kuma-ui/kuma-ui/issues/256, but first I wanted to be able to easily assert that existing usage was not broken.
As a sample test, I have added the test code for the Box component.
If this plan is acceptable, I will expand the test code for other components 👍🏻

test(core): setup @testing-library/jest-dom and add component test for Box

---

website/src/pages/docs/install.mdx

#264
This PR adds some instructions to integrate Kuma UI with Storybook to Installation document.

docs: add section of "Integrate with Storybook"

---

.changeset/brave-items-remain.md
packages/compiler/src/collector/expression.ts

This PR enhances `handleJsxExpression` to support static analysis of BinaryExpressions within JSX props, allowing for arithmetic operations to be evaluated at compile-time.
**Example:**
Previously, expressions like `<Text fontSize={2 + 5} />` weren't statically extractable. With this update, the above JSX will be recognized and evaluated as having a fontSize of `7`.

Add support for BinaryExpressions in handleJsxExpression

---

.changeset/brown-squids-brake.md
packages/core/src/components/Spacer/spacer.test.tsx
packages/core/src/tests/vitest.setup.ts

Minor modifications were made to the test cases in accordance with https://github.com/kuma-ui/kuma-ui/pull/278 .
- test(core): Run cleanup() on all test cases beforeEach
- fix(core): Replace `getComputedStyle` with `toHaveStyle` from `testing-library/jest-dom`

chore: modified existing test cases with the introduction of `testing-library/jest-dom`

---

.changeset/afraid-items-sort.md
example/vite/kuma.config.ts
example/vite/src/App.tsx
packages/core/src/theme.test.ts
packages/sheet/src/theme.ts
packages/system/src/column.ts
packages/system/src/compose.ts
packages/system/src/flex.ts
packages/system/src/grid.ts
packages/system/src/space.test.ts
packages/system/src/space.ts
packages/system/src/valueConverters.test.ts
packages/system/src/valueConverters.ts
website/src/pages/docs/Theme/CustomizingTheme.mdx
website/src/pages/docs/Theme/ThemeTokens.mdx

Add `spacings` theme token for properties such as `margin`, `padding`, and more.
Mostly similar to #272 but I've introduced `ValueConverter` to simplify the transforming logic. So I'd like to get review of @taishinaritomi.

Add support for spacing token

---

.codesandbox/ci.json
example/vite/package.json

Deploys [our vite example](https://github.com/kuma-ui/kuma-ui/tree/main/example/vite) from codesandbox CI instead of general react example to ease the effort of checking the behavior.
https://github.com/kuma-ui/kuma-ui/pull/274#issuecomment-1676238005
https://github.com/kuma-ui/kuma-ui/pull/290#issuecomment-1684899949

deploy real example project to codesandbox

---

.github/workflows/release.yml

Followup #300
It seems that `NPM_TOKEN` is correct instead of `NODE_AUTH_TOKEN`.
Failed run: https://github.com/kuma-ui/kuma-ui/actions/runs/5965772915/job/16183953680

fix dev snapshot workflow

---

.github/actions/setup-pnpm/action.yml
.github/workflows/release.yml

This will be the final retry!! :bow:
changesets/action seems to create `.npmrc` only when it publish releases. So instead, create `.npmrc` by setup-node.

create npmrc by setup-node instead of changesets/action

---

.changeset/mighty-coats-breathe.md
packages/sheet/src/regex.test.ts
packages/sheet/src/regex.ts
packages/sheet/src/sheet.test.ts
packages/sheet/src/sheet.ts

Lookbehind assertion is not supported by Safari 16.3 (Released on Jan 23, 2023) or older. It causes errors: `SyntaxError: Invalid regular expression: invalid group specifier name.`
cf. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Lookbehind_assertion#browser_compatibility
This PR removes all of them.

Remove regex lookbehinds to support Safari 16.3 or older 

---

.changeset/bright-books-learn.md
packages/core/src/theme.ts

Currently we can't get any completion in `baseStyle` and `variants` of `kuma.config.js`.
With this PR, we can get completion of property names and values. Still cannot autocomplete custom token as it causes circular reference but it's better experience than `any` type.

Improve autocompletion experience of `baseStyle` and `variants`

---

packages/vite/package.json

This Pull Request addresses the issue of an incorrect `exports.types` path specified in the `packages.json` file.
The current incorrect path specification is causing issues with referencing TypeScript type definition files. This fix ensures that the correct type definition files are accessible.
The correct `exports.types` path has been updated.

fix(vite): fix incorrect exports.types path

---

.changeset/young-boats-perform.md
packages/core/tsup.config.ts

`vitest.setup.ts` is unnecessary for users but wrongly included in the distribution. This PR removes it.

Exclude vitest.setup.ts from dist files

---

.github/workflows/main.yml
.github/workflows/release.yml

Use current LTS Node.js v18 to make build faster and ensure kuma works on v18

Run CI with node v18

---

.changeset/silly-penguins-impress.md
example/vite/.gitignore
example/vite/kuma.config.ts
example/vite/src/App.tsx
package.json
packages/babel-plugin/src/__test__/__snapshots__/component.test.ts.snap
packages/babel-plugin/src/__test__/component.test.ts
packages/compiler/src/extractor/extract.ts
packages/core/src/components/types.ts
packages/core/src/index.ts
packages/core/src/theme.ts
packages/sheet/src/theme.ts
website/src/pages/docs/Theme/ComponentTheme.mdx
website/src/pages/docs/Theme/CustomizingTheme.mdx

#303
Introduce `defaultProps` to allow users to define default properties for each component.
```js
const theme = createTheme({
components: {
Text: {
baseStyle: {
textDecoration: "underline",
},
variants: {
primary: {
color: "green",
},
secondary: {
color: "blue",
},
},
defaultProps: {
variant: "primary",
textDecoration: "line-through",
fontSize: "16px",
},
},
},
});
```
Then the CSS for `<Text />` will be like `{ color: green;text-decoration: line-through;font-size: 16px; }`.

Introduce `defaultProps` in component theme

---

.changeset/sour-ducks-knock.md
packages/core/src/theme.test.ts
packages/core/src/theme.ts

The type of theme property values was changed in https://github.com/kuma-ui/kuma-ui/pull/306 from being returned as primitive types to being returned as literal types.

improve createTheme type

---

.changeset/friendly-horses-cough.md
.gitignore
packages/babel-plugin/src/__test__/css.test.ts
packages/babel-plugin/src/__test__/styled.test.ts
packages/sheet/src/placeholders.test.ts
packages/sheet/src/placeholders.ts
packages/sheet/src/sheet.test.ts
packages/sheet/src/sheet.ts
packages/sheet/src/theme.ts

As per https://github.com/kuma-ui/kuma-ui/issues/318 I have added tokens placeholders you can use in css
```
css`
color: t("color.primary");
background-color: t("c.primary");
@media (max-width: t("b.sm")) {
margin-top: t(2);
}
`
```
Will generate CSS
```
color: red;
background-color: red;
@media (max-width: 800px) {
margin-top: 16px;
}
```
What is supported
- `t("<token>.<key>")` any token specified in kuma.config.js
- ~`t("c.<key>")` and `t("b.<key>")` shortcuts for colors and breakpoints~
- ~`t(2)` scaling factor like https://mui.com/material-ui/customization/spacing/ . Right now, it is hardcoded as 8px, but it is supper easy to add config to kuma.config~

#318 Theme tokens support

---

.changeset/flat-impalas-drum.md
packages/system/src/compose.ts

I have improved type autocompletion for Styled Props when configuring the following themes:
- radii
- sizes
- zIndices

fix: improve theme type for theme autocomplete to work

---

.changeset/clean-wombats-destroy.md
.eslintignore
example/vite/src/App.tsx
packages/core/src/components/Box/react/DynamicBox.tsx
packages/core/src/components/Box/react/StaticBox.tsx
packages/core/src/components/Box/react/index.tsx
packages/core/src/components/Button/react.tsx
packages/core/src/components/Flex/react.tsx
packages/core/src/components/Grid/react.tsx
packages/core/src/components/HStack/react.tsx
packages/core/src/components/Heading/handler.ts
packages/core/src/components/Heading/react.tsx
packages/core/src/components/Image/react.tsx
packages/core/src/components/Input/react.tsx
packages/core/src/components/Link/react.tsx
packages/core/src/components/Select/react.tsx
packages/core/src/components/Spacer/react.tsx
packages/core/src/components/Text/react.tsx
packages/core/src/components/VStack/react.tsx
packages/core/src/components/forwardRef.ts
packages/core/src/components/types.ts
packages/core/src/tests/vitest.setup.ts

Fix #256 
This PR introduces the use of `forwardRef` in our components.
The `forwardRef` implementation is based on Chakra UI's solution found at:
[Chakra UI forwardRef Implementation](https://github.com/chakra-ui/chakra-ui/blob/main/packages/core/system/src/forward-ref.tsx)

Implement ForwardRef in Components

---

.changeset/ten-pens-smile.md
example/vite/src/App.tsx
packages/core/src/components/Box/react/box.test.tsx
packages/core/src/components/types.ts

Fix https://github.com/kuma-ui/kuma-ui/pull/343#pullrequestreview-1651872055

Override original prop types with `as` component props

---

website/src/components/home/hero.tsx

I Fixed https://github.com/kuma-ui/kuma-ui/issues/239
- <img width="1014" alt="スクリーンショット 2023-10-20 23 55 26" src="https://github.com/kuma-ui/kuma-ui/assets/50833174/110c4ffa-0174-4991-8517-7063efd2b805">
Regardless of the aspect ratio, the effect will not be cut off.
The current code does not reproduce the background effect accurately.
Using the following code might reproduce the design more precisely; however, there's a concern that the code is complex and challenging to read
```
radial-gradient(circle at calc(calc(calc(100vw - 200px) * 0.75) + 100px) calc(calc(calc(100vh - 200px) * 0.5) + 100px), #bcf0f5, hsla(0, 0%, 100%, 0) calc(calc(100% - 100px) * 0.25)), radial-gradient(circle at calc(calc(calc(100vw - 200px) * 0.6) + 100px) calc(calc(calc(100vh - 200px) * 0.3) + 100px), #bce2f5, …
```

Ensure the background effects are fully visible regardless of the aspect ratio

---

.changeset/hot-insects-poke.md
example/next-app-router/package.json
example/vite/src/App.tsx
packages/babel-plugin/src/__test__/__snapshots__/component.test.ts.snap
packages/babel-plugin/src/__test__/__snapshots__/css.test.ts.snap
packages/babel-plugin/src/__test__/__snapshots__/k.test.ts.snap
packages/babel-plugin/src/__test__/__snapshots__/styled.test.ts.snap
packages/babel-plugin/src/ensureReactImport.ts
packages/compiler/src/__test__/__snapshots__/styled.test.ts.snap
packages/compiler/src/processTaggedTemplateExpression.ts

This PR allows Kuma UI's styled components created through the `styled` API to accept refs without triggering warnings. The unique alias assures that user-defined variable names are not in conflict with Kuma's internal usage of React.
- Adjusted [`ensureReactImport`](https://github.com/kuma-ui/kuma-ui/blob/main/packages/babel-plugin/src/ensureReactImport.ts) to import React as `__React_Kuma_`.
- Modified [`replaceTaggedTemplate`](https://github.com/kuma-ui/kuma-ui/blob/main/packages/compiler/src/processTaggedTemplateExpression.ts) to use `__React_Kuma_.forwardRef` enabling the passing of refs.

Enable `forwardRef` Usage in Components Created through the `styled` API

---

website/src/pages/docs/Recepies/Linting.mdx

This PR fixes the type in the Documentation > Recepies >Linting.

fix(docs): fix typo in linting docs

---

.changeset/old-buckets-laugh.md
packages/core/src/themeTokens.ts
packages/system/src/generator.ts

Refer to: https://github.com/kuma-ui/kuma-ui/issues/353
The style generator incorrectly matches expressions like `url(./image.png)` as custom styles. Because custom styles cannot be used within the CSS value function, I have added additional conditional checks for this case.
However, I believe this is a workaround and perhaps we should consider refactoring the logic in L37?

fix: background-image property unable to use `url()`

---

.changeset/tiny-pots-sparkle.md
packages/core/src/components/Box/react/utils.ts

Fix `Error: StyleSheetRegistry: id: `` not found in idIndexesMap.` error.
This error occurs on unmounting the code below. This is because Kuma renders DynamicBox despite the generated CSS will be empty.
```tsx
const isHoge = false;
<Box color={isHoge ? "red" : undefined} />;
```
This PR fixes `hasDynamicProps` to be more strict.

avoid false-positive hasDynamicProps

---

.codesandbox/ci.json

Now, since 2023-09-11, Node.js 16 is no longer LTS version.
When it is also considered that Node.js v18 is used for PR Checks or releasing,
I believe it would be better to use Node.js 18 for codesandbox too.
([Conversation on the relevant in Discord](https://ptb.discord.com/channels/1119672933477011598/1127180003872886794/1177504083737858118))

chore: Use Node.js 18 for codesandbox

---

.changeset/friendly-eggs-look.md
packages/vite/package.json

As the title says.
Vite 5 was recently released and is working fine on my end.
If there are no problems, I would be willing to include Vite 5 in the support.

chore(vite): specify vite version as a peer-dependency

---

.changeset/wet-lamps-grin.md
packages/system/src/generator.test.ts
packages/system/src/generator.ts

fix: https://github.com/kuma-ui/kuma-ui/issues/376
The original process would have overwritten all objects if the theme token had been applied to the pseudo-class.
Changed to add properties to objects.

fix:apply theme tokens to pseudo-class

---

website/src/pages/docs/install.mdx

`KumaUIWebpackPlugin` currently does not accept arguments, so the documentation has been modified accordingly.
- ref: https://github.com/kuma-ui/kuma-ui/pull/337

docs(install): remove unnecessary argument

---

.changeset/eleven-papayas-try.md
packages/core/src/registry/sheet/ClientStyleSheet.ts
packages/core/src/registry/sheet/ServerStyleSheet.ts

The index of rules can be `-1` if the insertion fails.
https://github.com/kuma-ui/kuma-ui/blob/0013d4a17aaafa94e95e5adb404c6f3111e6563a/packages/core/src/registry/sheet/ClientStyleSheet.ts#L64-L76
Then, deleting them [here](https://github.com/kuma-ui/kuma-ui/blob/cb37a56310bb412801e96302c7f41176c068ae7c/packages/core/src/registry/StyleSheetRegistry.ts#L66) results in the error below.
```
DOMException: Failed to execute 'deleteRule' on 'CSSStyleSheet': The index provided (4294967295) is larger than the maximum index (0).
```
Fixing it by just ignoring negative index on deletion.

Fix the error on invalid style

---

example/next-app-router/.gitignore
example/next-app-router/next.config.mjs
example/next-app-router/src/app/layout.tsx
example/next-app-router/src/app/page.tsx
packages/next-plugin/src/index.ts
packages/webpack-plugin/assets/package.json
packages/webpack-plugin/src/loader.ts
packages/webpack-plugin/src/plugin.ts

([PR #337](https://github.com/kuma-ui/kuma-ui/pull/337)) implemented an approach to handle style updates in development environments. This method involved appending extracted CSS to SearchParams, like so:
```ts
const importCSS = `import ${JSON.stringify(
`${this.utils.contextify(this.context, CSS_PATH)}?${params.toString()}`,
)};`;
callback(null, `${result.code}\n${importCSS};`);
```
However, we observed that style changes in Client Components did not reflect without a reload when using this approach.
To address this, we initially attempted to trigger Next.js's HMR by applying arbitrary changes to the actual CSS file set as Entry whenever there were style changes, as described below:
```ts
if (plugin.watchMode) {
/**
* In Next.js version 13.5 and later, changes made in virtual files are …
```

Temporary Workaround for HMR in Next.js Client Components with Real CSS Output

---

website/src/pages/docs/install.mdx

While reviewing the documentation for kuma-ui, I noticed that there was a reference to a non-existent option in the Vite plugin section. Therefore, I created a Pull Request to remove that reference.
https://github.com/kuma-ui/kuma-ui/blob/0bcf3b0c1dbcba43d4620219f9031d366365d3e6/packages/vite/src/index.ts#L9-L12

docs(website): remove references to non-existent options in install.mdx

---

.changeset/thin-toys-collect.md
packages/core/src/css.test.ts
packages/core/src/css.ts
website/src/pages/docs/API/css.mdx

https://emotion.sh/docs/@emotion/css#cx
Emotion has a `cx` utility function that merges multiple class names. Now, while this function doesn’t do nearly as much (their `cx` function also ensures styles are applied and take priority from left-to-right), having an out-of-the-box (albeit dumb) `cx` function to apply multiple class names would be great. 
```tsx
<div
className={cx(
css`
font-size: 18px;
color: blue;
`,
isLoggedIn &&
css`
color: red;
`
)}
/>
```

Add `cx` function for merging multiple class names

---

.changeset/pink-olives-perform.md
Cargo.lock
example/next-app-router/src/app/page.tsx
example/vite/src/App.tsx
example/vite/vite.config.ts
packages/compiler/src/__test__/__snapshots__/compileSync.test.ts.snap
packages/compiler/src/__test__/__snapshots__/css.test.ts.snap
packages/compiler/src/__test__/__snapshots__/k.test.ts.snap
packages/compiler/src/__test__/css.test.ts
packages/compiler/src/__test__/k.test.ts
packages/wasm/Cargo.toml
packages/wasm/package.json
packages/wasm/src/lib.rs
packages/wasm/src/transform/visit/collect_import_bindings.rs
packages/wasm/src/transform/visit/ensure_react_import.rs
packages/wasm/src/transform/visit/import_box.rs
packages/wasm/src/transform/visit/replace_k_with_box.rs
packages/wasm/src/util/mod.rs

close #415 
The previous version of oxc (v0.12.5) rendered non-English characters as escape sequences, so this PR updates oxc (which `@kuma-ui/wasm` depends on to parse JS/TS) to the latest version.

Update oxc From v0.12.5 to v0.25.0

---

.changeset/little-spies-join.md
example/vite/package.json
packages/vite/package.json
pnpm-lock.yaml

- Added [Vite v6](https://vite.dev/blog/announcing-vite6), released on 2024/11/26, to the peerDependencies of the Vite plugin.
- Also updated the example (I can rebase it if unnecessary 🙏).
- Running pnpm install updated the lock file. Should I exclude this? (The version of pnpm I’m using is v9.14.2).
Tested it under /example/vite, and it seems to be working without any issues!

peerDependencies add vite v6
